
# Local(로컬 환경, default), Dev(개발 환경), Prod(운영 환경)
# ex)))) java -jar test-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
# ex)))) ./gradlew bootRun --args='--spring.profiles.active=dev'

# 기본값은 local 프로파일로 설정
spring:
  application:
    name: profile-test

---
spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local, dev, prod